### ISSUE TITLE
TransitStopFacilities that have no Route

### ISSUE THREAD

**Issue by jfbischoff** [SchweizerischeBundesbahnen/matsim-sbb-extensions#1]
Hi,
I played a little bit around with the SwissRaptor - really nice work, thank you, SBB! For my sample scenario, I could measure a speed up of  up roughly 8 times, amazing!

I noticed one little bug - not sure if we should call it like that or not: If there are StopFacilities in the transit schedule, that are not part of any route, the Router crashes with a  NPE in SwissRailRaptorData at line 213, because toRouteStopIndices == null. 
This is a somewhat an extreme case, but apparently GTFS converters spit out these stop facilities quite often. 
I'm therefore not so sure, whether you should support this on the router side or demand stricter transit schedules (in the latter case, we should move this discussion to JIRA, I guess).

What is your opinion?

**Comment by mrieser** [comment]
The issue was fixed in commit 9933cb3b0309d723900f945fbeaf88f60f7c4584 and is contained in the release 0.9.2.
