### ISSUE TITLE
Incoherent travel times between zones

### ISSUE THREAD

**Issue by Kamil-Mo** [SchweizerischeBundesbahnen/matsim-sbb-extensions#105]
Hello, we are using in my research team the SBB MATSim extension in order to compute matrices with the travel times between defined zones. Due to limited RAM, we ran the method calculatePTMatrices (from the class CalculateSkimMatrices) considering only 1 location per zone and an endTime = startTime + 5 min, and also only walking (no bike).

The results surprised us, for many aspects:
- many zones combinations have a infinite travel time (usually when the destination zone is at least 100 km away from the origin zone), even if it should be possible to reach these zones in a short time
- the travel time from a zone A to a zone B is sometimes 3 times bigger than from B to A (e.g. 10 hours against 3h)
- even if one zone does not have any access to public transport (in our model), the travel times from this zone to the other zones are close to reality, which should not be the case since in that origin zone no public transport is modeled in our case.

Do you have any potential explanation to these points?

Thanks a lot in advance for your time and your help.

**Comment by mrieser** [comment]
> and an endTime = startTime + 5 min

This will likely not work. When there is no departure within this 5 minutes, it means that no connection will be found, thus resulting in the infinite travel times. The time window should be as big to catch at least one service. Depending on the model area, a typical bus or train line might have departures every 30 or 60 minutes, so the time window should also be at least as big. Personally, I would go with at least 60 minutes.

This might also explain the different travel times in different travel directions. If the only departure within those 5 minutes is a train leaving in the opposite direction, it might take very long to actually reach the destination zone.

Regarding zones without access to PT: The algorithm searches for each sampling point (in your case the 1 location per zone) the nearest transit stops to search for PT routes. Those stops can also be located outside the zone in a neighboring zone, if they are still more or less close-by. This might explain why you find zones without PT stops still providing a useful travel time.

**Comment by Kamil-Mo** [comment]
Thank you very much for your answer. We will to follow your advice and run it for a much longer period and come back to you if it does not help 👍
