### ISSUE TITLE
Bintray

### ISSUE THREAD

**Issue by sebhoerl** [SchweizerischeBundesbahnen/matsim-sbb-extensions#11]
Would there be any chance to deliver the package using Bintray or another maven repository? It is a bit annoying just having Jitpack, because the identifier of the package is actually

```
	<groupId>ch.sbb</groupId>
	<artifactId>matsim-sbb-extensions</artifactId>
	<version>0.10.1</version>
```

while I have to include it via Jitpack as

```
		<dependency>
			<groupId>com.github.SchweizerischeBundesbahnen</groupId>
			<artifactId>matsim-sbb-extensions</artifactId>
			<version>0.10.1</version>
		</dependency>
```

Apart from the fact that I'm a bit skeptical about relying on another third-party service to deliver the packages I also think it introduces a lot of inconsistency.

One example: If I use SwissRailRaptor, but I get an error message (because I set up something wrongly etc.), Eclipse will show me an error, for instance a NullPointerException somewhere in SwissRailRaptor. To know what I have to fix I could usually just click on the error and Eclipse would show me the source location. Unfortunately, it is (rightly so) not able to do so, because the error occured in "com.github.*" and not in "ch.sbb.*", which I may have open as a project as well. So what I need to do is to find the file and the line manually.... Not a huge problem, but still a bit of an annoyance.

Setting up a repository on Bintray is actually a matter of minutes, so maybe it's something to consider?

**Comment by deuxnids** [comment]
Hi @sebhoerl,
We understand your problem and we will try find a quick fix.

**Comment by sebhoerl** [comment]
Great!
