### ISSUE TITLE
SwissRailRaptorConfigGroup in conflict with its matsim copy

### ISSUE THREAD

**Issue by michalmac** [SchweizerischeBundesbahnen/matsim-sbb-extensions#114]
`SwissRailRaptorConfigGroup` in matsim-sbb-extensions is in conflict with `SwissRailRaptorConfigGroup` in matsim. Would it be possible to remove it from this repo? I do not see it is directly used anywhere here.

**Comment by jfbischoff** [comment]
Thanks for pointing out, Michal 👍 
I'm removing it.

**Comment by michalmac** [comment]
Nice, 12.13 is already released! That was quick 🚀  Thanks!

**Comment by jfbischoff** [comment]
It's always better to get these things done before the weekend :-)
