### ISSUE TITLE
RIntermodalAccessEgress does not allow for person-specific parameters

### ISSUE THREAD

**Issue by sebhoerl** [SchweizerischeBundesbahnen/matsim-sbb-extensions#12]
`Person` should be passed to `RaptorIntermodalAccessEgress::calcIntermodalAccessEgress`, otherwise person-specific scoring parameters cannot be used to evaluate different access/egress options.

**Comment by sebhoerl** [comment]
I just did some more digging, and it seems that already the `RaptorParameters` are those derived from `RaptorParametersPerPerson`, just that the default implementation `DefaultRaptorParametersForPerson` does not actually take into account subpopulations. Probably this should be changed? Also, I cannot find any other implementation. Shouldn't the SwissRailRaptor compute the actual parameters from the subpopulation to be consistent with scoring?

**Comment by mrieser** [comment]
Fixed by [some PullRequest](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/commit/030c9509fd40e54ffb07bafaabcabe153ccd6a13).
