### ISSUE TITLE
Parameters for "transit_walk" are not used for transfer legs in routing

### ISSUE THREAD

**Issue by sebhoerl** [SchweizerischeBundesbahnen/matsim-sbb-extensions#13]
We just noticed that the parameters for "transit_walk" don't seem to be used for routing. Instead the normal "walk" parameters are used. 

Specifically, the costs for tranfers seem to be calculated here:
https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/master/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java#L645

There `transfer.transferCost` is used, which is precalculated here:
https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/0.10.1/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java#L266

The `transferUtilPerS` comes from the `RaptorStaticConfig`:
https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/0.10.1/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java#L223

Which is set up here:
https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/0.10.1/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorUtils.java#L47

So there are two problems:
- There is no way to specifically set a utility for transit_walk
- By default, right now there is no distinction between any walk (also not for access or egress), all use the same parameters from "walk"
- Furthermore, all use the "standard" parameters, which are not user-dependent.

*Proposal*

1. I just did a quick check and `RTransfer.transferCost` is never used anywhere than in the spot outlined above. Is there anything that speaks against using the `RaptorParameters` there to just calculate `transfer.transferTime * raptorParams.getMarginalUtility...(TransportMode.transit_walk)` ?
2. Anything that speaks against fixing `RaptorUtils`, so it uses different modes? Also this would be more consistent between `RaptorStaticConfig` and `RaptorParameters`
3. Wouldn't it make sense to remove those getters for the utilities from RaptorStaticConfig altogether and refactor the code so that always `RaptorParameters` are used, which can be person-specific?

**Comment by sebhoerl** [comment]
While writing the PR is also noticed that `RTransfer.transferTime` could be individualized in a similar way. What I would put there is the time from the schedule, otherwise -1. Then in `SwissRailRaptorCode` I would do the checks if some agent, dependent on its beeline walk speed, would take longer. Should I add this?

**Comment by mrieser** [comment]
Thanks, I've merged your changes into my 0.11.0-SNAPSHOT branch and added some minor optimization to it. I plan to tag it early next week to provide an up-to-date weekly release.
Do you need a 0.10-compatible version as well?

**Comment by sebhoerl** [comment]
0.11.0 is fine, thanks!
