### ISSUE TITLE
Make RaptorStaticConfig injectable

### ISSUE THREAD

**Issue by sebhoerl** [SchweizerischeBundesbahnen/matsim-sbb-extensions#14]
So far `RaptorStaticConfig` is hardcoded:
https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/master/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorFactory.java#L47

An easy improvement would be to write a provider for `RaptorStaticConfig` and inject it in `SwissRailRaptorFactory`.

**Comment by mrieser** [comment]
What would be the use-case?

RaptorStaticConfig merely collects configuration settings from other places and makes them more easily available. And thus I see it more as an internal data structure for easy access to the values, but not as a user-facing interface. Everything that can be configured in RaptorStaticConfig should come from other Config modules, so I wonder what the use-case is to make it replaceable by injection.

**Comment by sebhoerl** [comment]
The standard version assigns the same utilities for all walk modes:
https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/master/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorUtils.java#L47

If it would be injectable I could define for myself where these values come from (which in my use case would be to use the actual values for those modes).

**Comment by mrieser** [comment]
okay, I see, subpopulations (or whatever specialization) are not taken into account.
Having had a look at PR #16 by now, is this still necessary? As #16 actually removes all these marginal-walk-utilities and moves them to RaptorParameters.
