### ISSUE TITLE
jitpack MissingArtifact build problem

### ISSUE THREAD

**Issue by davibicudo** [SchweizerischeBundesbahnen/matsim-sbb-extensions#2]
Hi,
The issue after adding the dependencies to the pom.xml was:

Missing artifact com.github.SchweizerischeBundesbahnen:matsim-sbb-extensions:jar:0.9.2

The same problem as here: https://stackoverflow.com/questions/36284156/cant-build-using-jitpack-io

Then somewhere I found that replacing the "version" for the "tag" would work and it did. It's not clear to me what the real issue is or why changing to tag solved but I'm posting it here in case someone else has the same issue.

**Comment by deuxnids** [comment]
Hi @davibicudo,

You're right we had some issue with the 0.9.2 build. Thanks for the info.

 We deleted the build and force it to rebuild on jitpack. It seems to be working now. But you may need to delete the previous 0.9.2 downloaded artifact. 

Let me know.

**Comment by davibicudo** [comment]
Hi @deuxnids,
It worked. Thanks!
