### ISSUE TITLE
Transit_walk problem

### ISSUE THREAD

**Issue by MAlbertini95** [SchweizerischeBundesbahnen/matsim-sbb-extensions#65]
Hi everybody! Fisrt of all, thanks for developing the SBB raptor extension, it's very powerful and it's making simulation much more faster. 
I'm using MATSim 11.0 and SBB extension 11.6. I'm trying to use the transit router, but I notice that if If I add the intermodal access/egress from the conifg group, then all agents use transit walk instead of pt. This is also an open issue on Matsim main distribution, which I report here:
[https://github.com/matsim-org/matsim-code-examples/issues/218#issue-508711280](url)

I wonder how it is possible to solve this. Is it just a matter of the MainModeIdentifier ( I saw the Implemented class in the dependencies, so I guess the MainModelIdentifierImpl is active ) or some other problem? Because I notice that the global share for pt ( which is the analyzed mode ) and normal walk are always very similar. Hope someone can help! thank you

**Comment by mrieser** [comment]
Hi. Without access to your scenario it's difficult to say why it is not working. As the functionality is used in other scenarios successfully, it's probably a configuration issue.

SwissRailRaptor has been moved into the MATSim main repository and is now maintained over there, kept compatible with all the other changes happening in MATSim. You might want to try the latest weekly release of MATSim, which includes SwissRailRaptor, and see if the problem persists. If it does, feel free to ask again on [MATSim's issue tracker](https://www.matsim.org/faq).
